In [1]:
import numpy as np

In [2]:
myarr = np.array([5,6,7,3,23])
myarr

array([ 5,  6,  7,  3, 23])

In [3]:
myarr[0]

5

In [4]:
type(myarr)

numpy.ndarray

In [5]:
myarr.shape

(5,)

In [6]:
# 2D
myarr2 = np.array([[3,4,5,6,7]], dtype='int64')

In [7]:
myarr2

array([[3, 4, 5, 6, 7]], dtype=int64)

In [8]:
type(myarr2)

numpy.ndarray

In [9]:
myarr2.shape

(1, 5)

In [10]:
myarr2[0]

array([3, 4, 5, 6, 7], dtype=int64)

In [11]:
myarr2[0,2]

5

In [12]:
myarr.dtype

dtype('int32')

In [13]:
myarr2.dtype

dtype('int64')

# Change an element

In [14]:
myarr[2] = 45
myarr

array([ 5,  6, 45,  3, 23])

In [15]:
myarr2[0,1] = 66
myarr2

array([[ 3, 66,  5,  6,  7]], dtype=int64)

# Array creation: from other python objects

In [16]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [19]:
np.array({12,34,34})

array({34, 12}, dtype=object)

avoid using obect types... try and use integers and floats as much possible

## Intrinsic methods:

In [20]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
rng = np.arange(13)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

its like a range function in python but an array

In [23]:
lspace = np.linspace(1,6,5)
lspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

gives equal space between 2 elements, first element in bracket is start point, second point is end point and 3rd point is number of splits

In [24]:
emp = np.empty((4,6))
emp

array([[4.67296746e-307, 1.69121096e-306, 7.56595733e-307,
        7.56587585e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06612616e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 1.11261162e-306, 1.78021527e-306]])

In [25]:
emp_like = np.empty_like(lspace)
emp_like

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

creates empty list and empty_like can copy any previous array

# Identity Matrix:

In [26]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
ide.shape

(5, 5)

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

to create identity matrix

# Reshaping:

In [29]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr = arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.shape

(99,)

In [35]:
brr = arr[np.newaxis, :]
brr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98]])

In [36]:
brr = arr[:, np.newaxis]
brr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64],
       [65],
       [66],
       [67],
       [68],
       [69],
       [70],
       [71],
       [72],
       [73],
       [74],
       [75],
       [76],

In [37]:
brr.shape

(99, 1)

In [38]:
x = [[1,2,3], [4,5,6], [7,1,0]]
ar = np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
ar.sum(axis=0)

array([12,  8,  9])

In [42]:
ar.flat

In [43]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [44]:
ar.ndim

2

In [45]:
ar.size

9

In [46]:
ar.nbytes

36

In [47]:
one = np.array([1,3,4,34,2])

In [48]:
one.argmax()

3

In [49]:
one.argmin()

0

In [50]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

argmax gives index of largest element, argmin give index of smallest element, argsort gives the sorting order of idicies

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.argmax()

6

In [53]:
ar.argmin()

8

In [54]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [55]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [56]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [57]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [58]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [59]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [60]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

for 2D arrays you have to specify axis aswell

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [3, 1, 7]])

In [63]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [3, 1, 7]])

In [64]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [10,  2,  7]])

In [65]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [21,  1,  0]])

In [66]:
ar.sum()

29

In [67]:
ar2.sum()

25

In [68]:
ar.max()

7

In [69]:
ar2.min()

0

In [70]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [71]:
np.where(ar2<3)

(array([0, 0, 0, 1, 2], dtype=int64), array([0, 1, 2, 1, 1], dtype=int64))

In [72]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [3, 1, 7]])

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
np.count_nonzero(ar)

8

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

# DotProduct

In [76]:
l1 = [1,2,3]
l2 = [4,5,6]

In [77]:
a1 = np.array(l1)
a1

array([1, 2, 3])

In [78]:
a2 = np.array(l2)
a2

array([4, 5, 6])

In [79]:
# dot = 0
# for i in range(len(l1)):
#     dot += l1[i] * l2[i]
# print(dot)

dot = np.dot(a1, a2)
print(dot)

# sum1 = a1 * a2
# dot = np.sum(sum1)
# print(dot)

dot = a1 @ a2
print(dot)

32
32


# Fancy Indexing

In [80]:
d = np.array([23,34,45,56,67])
e = [1,2,4]
d[e]

array([34, 45, 67])

[rows, columns]
[start_row : end_row, start_column : end_column]

In [81]:
even = np.argwhere(d%2 == 0).flatten()
print(d[even])

[34 56]


flatten changes it into 1D array

# Concatenation:

In [82]:
a = np.array([[2,3], [4,5]])
b = np.array([[1,7]])

c = np.concatenate((a,b.T), axis=1)
print(c)
c = np.concatenate((a,b), axis=0)
print(c)
c = np.concatenate((a,b), axis=None)
print(c)

[[2 3 1]
 [4 5 7]]
[[2 3]
 [4 5]
 [1 7]]
[2 3 4 5 1 7]


In [83]:
# hstack and vstack

In [84]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(c)
c = np.vstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


# Broadcasting:

In [85]:
x = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6]])
# a = np.array([[1,0,1],[1,0,1],[1,0,1],[1,0,1]]) instead of doing all this we can do
a = np.array([1,0,1])
y = x + a
print(y)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


# Functions and Axis

1 D = Only axis=0

2 D = axis=0 and axis=1

axis=0 is going down column wise 

axis=1 is going from left to right row wise -->

In [86]:
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])
a

array([[ 7,  8,  9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21, 22, 23]])

In [87]:
a.sum()

210

In [88]:
a.sum(axis=None)

210

In [89]:
np.sum(a, axis=0)

array([24, 26, 28, 30, 32, 34, 36])

In [90]:
np.sum(a, axis=1)

array([ 70, 140])

In [91]:
a.mean()

15.0

In [92]:
a.mean(axis=0)

array([12., 13., 14., 15., 16., 17., 18.])

In [93]:
np.mean(a, axis=1)

array([10., 20.])

In [94]:
a.var()

29.0

In [95]:
a.std()

5.385164807134504

In [96]:
a.min(axis=1)

array([ 7, 17])

In [97]:
a.max(axis=0)

array([17, 18, 19, 20, 21, 22, 23])

In [98]:
np.argmin(a, axis=0)

array([0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [99]:
np.argmax(a, axis=1)

array([6, 6], dtype=int64)

argmin gives index value where the value is smallest and argmax gives the index value where the value is biggest

# Masks

In [100]:
a = np.array([1,2,3,4,5])
a < 3

array([ True,  True, False, False, False])

In [101]:
a > 3

array([False, False, False,  True,  True])

In [102]:
a[a<3]

array([1, 2])

gives the values where the condition is true

In [103]:
np.where(a > 3,30,20)

array([20, 20, 20, 30, 30])

where a is greater then 3 we replaced it with 30 and where the condition didnt meet we replaced it with 20 ... a > 3,30,20

# Data Types:

In [104]:
a = np.array([2.0, 3.0])
print(a)
print(a.dtype)

[2. 3.]
float64


we can force change the dtype by passing the values

In [105]:
a = np.array([2.0, 3.0], dtype=np.int64)
print(a)
print(a.dtype)

[2 3]
int64


# Copying Arrays:

In [106]:
a = np.array([1,2,3])
b = a
b[0] = 42
print(b)
print(a)

[42  2  3]
[42  2  3]


make a copy

In [107]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 42
print(b)
print(a)

[42  2  3]
[1 2 3]


# Random Arrays:

In [108]:
np.random.random((2,3))

array([[0.26727094, 0.7351465 , 0.41814231],
       [0.42734146, 0.80432258, 0.20444266]])

this will generate uniform distribution between 0 and 1

In [109]:
a = np.random.randn(2,3)
print(a, a.mean(), a.var())

[[-1.79730856  0.17287351  0.22215046]
 [-0.84140931  0.05237534  1.84037645]] -0.05849035199338637 1.2311209501009828


rand or randn will give normal/gaussian distribution

with mean = 0 and variance = 1

In [119]:
a = np.random.randint(2,10, size=(3,3))
print(a)

[[8 2 4]
 [9 8 5]
 [9 8 6]]


first number is lower bound which is included, second number is upper bound and not included, if only one number is given then lower bound is 0

In [122]:
a = np.random.choice(20, size=10, replace=True)
print(a)

[ 3  9  4 12 16  2 15 12 12 17]


In [149]:
np.random.choice(3,13,1)

array([2, 0, 1, 0, 2, 2, 2, 0, 2, 2, 1, 1, 2])

In [161]:
np.random.choice(13,size=np.random.randint(3,13), replace=False)

array([ 8, 11,  1,  7])

In [112]:
a = np.random.choice([-2,3,5], size=15)
print(a)

[ 5 -2  3  3 -2 -2 -2 -2  5 -2  3  3 -2  5  3]


one number is passed and 0 is considered as lower bound, if list is provided then it only choses from the list given

# Eigenvalues and Eigenvectors

In [113]:
a = ([1,2], [3,4])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)

[-0.37228132  5.37228132]


In [114]:
print(eigenvectors) #column vectors

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Solving Linear Systems

Ax = b

x = A**(-1) * b

In [115]:
A = np.array([[1,1], [1.5,4.0]])
b = np.array([2200, 5050])

x = np.linalg.inv(A).dot(b)
print(x)

[1500.  700.]


In [116]:
np.linalg.solve(A,b)

array([1500.,  700.])

# Load Data

In [117]:
# np.laodtxt
# np.genfromtxt

# data = np.loadtxt('file_name.csv', delimeter= ",", dtype=float64)
# print(data)

# data = np.genfromtxt('file_name.csv', delimeter= ",", dtype=float64)
# print(data)

# Doc Strings

In [118]:
?a

question mark generates doc strings